title: Interview Preparation with Tyler
description: Let's learn to interview together!
google_analytics:
is_project_page: true
theme: jekyll-theme-cayman
repository: tylerthedeveloper/tylerthedeveloper.github.io
github:
  is_project_page: true
  repository_url: https://github.com/tylerthedeveloper/tylerthedeveloper.github.io
  repository_name: Tyler's Personal Site
include: ['_evans', '_interview', '_pages']

collections:
  interview:
    output: true
    permalink: /interview/:name
  evans:
    output: true
    permalink: /evans/:name

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "interview"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "evans"
    values:
      layout: "evans"
      
permalink: pretty
